### ISSUE TITLE
Chromeos

### ISSUE THREAD

**Issue by eepgwde** [codebuff/kronymous#5]
It has worked, then a Chromeos update (Peppy Dev) and no more.

Loading NaCl module.
Loaded tor.nexe [15740 KiB]                                                      
Nov 02 20:41:21.823 [notice] Tor v0.2.6.10 (git-cefb5f151f27c960) running on NaCl with Libevent 2.0.22-stable, OpenSSL 1.0.2e and Zlib 1.2.8.
Nov 02 20:41:21.824 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 02 20:41:21.848 [notice] Read configuration file "/mnt/http/tor/conf".
Nov 02 20:41:21.857 [notice] Opening Socks listener on 127.0.0.1:9999
Nov 02 20:41:21.860 [warn] /home/user/.tor is not owned by this user (<unknown>, -1) but by <unknown> (1001). Perhaps you are running Tor as the wrong user?

>> nacl sometimes doesn't set UID properly, ignoring...
Nov 02 20:41:21.861 [warn] Fixing permissions on directory /home/user/.tor
Nov 02 20:41:21.000 [notice] Parsing GEOIP IPv4 file /mnt/http/tor/geoip-files/geoip.
Nov 02 20:41:22.000 [notice] Parsing GEOIP IPv6 file /mnt/http/tor/geoip-files/geoip6.
Program (../tor.nmf) exited (status=126)

**Comment by kcoyner** [comment]
Same issue for me as well:

'''Loading NaCl module.
Loaded tor.nexe [15740 KiB]                                                      
Nov 16 10:37:41.298 [notice] Tor v0.2.6.10 (git-cefb5f151f27c960) running on NaCl with Libevent 2.0.22-stable, OpenSSL 1.0.2e and Zlib 1.2.8.
Nov 16 10:37:41.298 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 16 10:37:41.302 [notice] Read configuration file "/mnt/http/tor/conf".
Nov 16 10:37:41.311 [notice] Opening Socks listener on 127.0.0.1:9999
Nov 16 10:37:41.313 [warn] /home/user/.tor is not owned by this user (<unknown>, -1) but by <unknown> (1001). Perhaps you are running Tor as the wrong user?

>> nacl sometimes doesn't set UID properly, ignoring...
Nov 16 10:37:41.313 [warn] Fixing permissions on directory /home/user/.tor
Nov 16 10:37:41.000 [notice] Parsing GEOIP IPv4 file /mnt/http/tor/geoip-files/geoip.
Nov 16 10:37:41.000 [notice] Parsing GEOIP IPv6 file /mnt/http/tor/geoip-files/geoip6.
Nov 16 10:37:41.000 [notice] Bootstrapped 0%: Starting
Program (../tor.nmf) exited (status=126)
'''

**Comment by codebuff** [comment]
Continued here https://www.reddit.com/r/TOR/comments/5f1bq7/kronymous_status_updates_and_faqs/
